test optimize
set opt_level=speed
target x86_64

function %stack_load(i64) -> i64 {
  ss0 = explicit_slot 8

block0(v0: i64):
  stack_store.i64 v0, ss0
  v1 = stack_load.i64 ss0
  return v1
}

; check: function %stack_load(i64) -> i64 fast {
; nextln:    ss0 = explicit_slot 0
; check:  block0(v0: i64):
; nextln:     return v0
; nextln: }

function %interleaved_stack_stores(i64, i64) -> i64 {
  ss0 = explicit_slot 16

block0(v0: i64, v1: i64):
  stack_store.i64 v0, ss0+8
  stack_store.i64 v1, ss0
  v2 = stack_load.i64 ss0+8
  return v2
}

; check: function %interleaved_stack_stores(i64, i64) -> i64 fast {
; nextln:    ss0 = explicit_slot 0
; check:  block0(v0: i64, v1: i64):
; nextln:     return v0
; nextln: }

function %adjacent_narrow_stack_stores(i8, i8, i8, i8, i8, i8, i8, i8) -> i64 {
  ss0 = explicit_slot 8

block0(v0: i8, v1: i8, v2: i8, v3: i8, v4: i8, v5: i8, v6: i8, v7: i8):
  stack_store.i8 v0, ss0
  stack_store.i8 v1, ss0+1
  stack_store.i8 v2, ss0+2
  stack_store.i8 v3, ss0+3
  stack_store.i8 v4, ss0+4
  stack_store.i8 v5, ss0+5
  stack_store.i8 v6, ss0+6
  stack_store.i8 v7, ss0+7
  jump block1

block1:
  v8 = stack_load.i64 ss0
  return v8
}

; check: function %adjacent_narrow_stack_stores(i8, i8, i8, i8, i8, i8, i8, i8) -> i64 fast {
; nextln:    ss0 = explicit_slot 0
; check:  block0(v0: i8, v1: i8, v2: i8, v3: i8, v4: i8, v5: i8, v6: i8, v7: i8):
; nextln:     jump block1
; check:  block1:
; check:      v31 = iconst.i64 56
; nextln:     v29 = ishl v28, v31  ; v31 = 56
; nextln:     v30 = bor v27, v29
; nextln:     return v30
; nextln: }

function %multiple_stack_predecessors(i64, i64, i8) -> i64 {
  ss0 = explicit_slot 8

block0(v0: i64, v1: i64, v2: i8):
  brif v2, block1, block2

block1:
  stack_store.i64 v0, ss0
  jump block3

block2:
  stack_store.i64 v1, ss0
  jump block3

block3:
  v3 = stack_load.i64 ss0
  return v3
}

; check: function %multiple_stack_predecessors(i64, i64, i8) -> i64 fast {
; nextln:    ss0 = explicit_slot 8
; check:  block1:
; check:      store.i64 notrap v0,
; check:  block2:
; check:      store.i64 notrap v1,
; check:  block3:
; check:      v3 = load.i64 notrap
; nextln:     return v3
; nextln: }

function %overlapping_stack_store(i64, i32) -> i64 {
  ss0 = explicit_slot 8

block0(v0: i64, v1: i32):
  stack_store.i64 v0, ss0
  stack_store.i32 v1, ss0+4
  v2 = stack_load.i64 ss0
  return v2
}

; check: function %overlapping_stack_store(i64, i32) -> i64 fast {
; nextln:    ss0 = explicit_slot 8
; check:  block0(v0: i64, v1: i32):
; check:       store notrap v0,
; check:       store notrap v1,
; check:       v2 = load.i64 notrap
; check:       return v2
; nextln: }

function %address_taken_stack_slot(i64) -> i64 {
  ss0 = explicit_slot 8
  sig0 = (i64) system_v
  fn0 = %clobber sig0

block0(v0: i64):
  stack_store.i64 v0, ss0
  v1 = stack_addr.i64 ss0
  call fn0(v1)
  v2 = stack_load.i64 ss0
  return v2
}

; check: function %address_taken_stack_slot(i64) -> i64 fast {
; nextln:    ss0 = explicit_slot 8
; nextln:    sig0 = (i64) system_v
; nextln:    fn0 = %clobber sig0
; check:  block0(v0: i64):
; check:       store notrap v0,
; check:       call fn0(
; check:       v2 = load.i64 notrap
; check:       return v2
; nextln: }

function %direct_store_to_stack_load(i64) -> i64 {
  ss0 = explicit_slot 8

block0(v0: i64):
  v1 = stack_addr.i64 ss0
  store notrap v0, v1
  v2 = stack_load.i64 ss0
  return v2
}

; check: function %direct_store_to_stack_load(i64) -> i64 fast {
; nextln:    ss0 = explicit_slot 0
; check:  block0(v0: i64):
; nextln:     return v0
; nextln: }

function %stack_store_to_direct_load(i64) -> i64 {
  ss0 = explicit_slot 8

block0(v0: i64):
  stack_store.i64 v0, ss0
  v1 = stack_addr.i64 ss0
  v2 = load.i64 notrap v1
  return v2
}

; check: function %stack_store_to_direct_load(i64) -> i64 fast {
; nextln:    ss0 = explicit_slot 0
; check:  block0(v0: i64):
; nextln:     return v0
; nextln: }

function %direct_store_to_direct_load(i64) -> i64 {
  ss0 = explicit_slot 8

block0(v0: i64):
  v1 = stack_addr.i64 ss0
  store notrap v0, v1
  v2 = load.i64 notrap v1
  return v2
}

; check: function %direct_store_to_direct_load(i64) -> i64 fast {
; nextln:    ss0 = explicit_slot 0
; check:  block0(v0: i64):
; nextln:     return v0
; nextln: }

function %direct_store_to_reinterpreted_load(i64) -> i8x8 {
  ss0 = explicit_slot 8

block0(v0: i64):
  v1 = stack_addr.i64 ss0
  store notrap v0, v1
  v2 = load.i8x8 notrap v1
  return v2
}

; check: function %direct_store_to_reinterpreted_load(i64) -> i8x8 fast {
; nextln:    ss0 = explicit_slot 0
; check:  block0(v0: i64):
; nextln:     v3 = bitcast.i8x8 little v0
; nextln:     return v3
; nextln: }

function %escaped_direct_stack_address(i64) -> i64 {
  ss0 = explicit_slot 8
  sig0 = (i64) system_v
  fn0 = %clobber sig0

block0(v0: i64):
  v1 = stack_addr.i64 ss0
  store notrap v0, v1
  call fn0(v1)
  v2 = load.i64 notrap v1
  return v2
}

; check: function %escaped_direct_stack_address(i64) -> i64 fast {
; nextln:    ss0 = explicit_slot 8
; nextln:    sig0 = (i64) system_v
; nextln:    fn0 = %clobber sig0
; check:  block0(v0: i64):
; check:      store notrap v0,
; check:      call fn0(
; check:      v2 = load.i64 notrap
; nextln:     return v2
; nextln: }

function %escaped_direct_stack_address_through_block_arg(i64) -> i64 {
  ss0 = explicit_slot 8

block0(v0: i64):
  stack_store.i64 v0, ss0
  v1 = stack_addr.i64 ss0
  jump block1(v1)

block1(v2: i64):
  v3 = load.i64 notrap v2
  return v3
}

; check: function %escaped_direct_stack_address_through_block_arg(i64) -> i64 fast {
; nextln:    ss0 = explicit_slot 8
; check:  block0(v0: i64):
; check:      v4 = stack_addr.i64 ss0
; nextln:     store notrap v0, v4
; nextln:     jump block1
; check:  block1:
; nextln:     return v0
; nextln: }

function %reinterpreted_stack_load(i8x8) -> i64 {
  ss0 = explicit_slot 8

block0(v0: i8x8):
  stack_store.i8x8 v0, ss0
  v1 = stack_load.i64 ss0
  return v1
}

; check: function %reinterpreted_stack_load(i8x8) -> i64 fast {
; nextln:    ss0 = explicit_slot 0
; check:  block0(v0: i8x8):
; nextln:     v2 = bitcast.i64 little v0
; nextln:     return v2
; nextln: }

function %stack_map_stack_slot(i64) {
  ss0 = explicit_slot 8
  sig0 = () system_v
  fn0 = %safepoint sig0

block0(v0: i64):
  stack_store.i64 v0, ss0
  call fn0(), stack_map=[i64 @ ss0+0]
  return
}

; check: function %stack_map_stack_slot(i64) fast {
; nextln:    ss0 = explicit_slot 8
; nextln:    sig0 = () system_v
; nextln:    fn0 = %safepoint sig0
; check:  block0(v0: i64):
; check:       store notrap v0,
; check:       call fn0(), stack_map=[i64 @ ss0+0]
; check:       return
; nextln: }

function %shifted_one_is_nonzero(i64) -> i8 {
block0(v0: i64):
  v1 = iconst.i64 1
  v2 = ishl v1, v0
  v3 = iconst.i64 0
  v4 = icmp ne v2, v3
  return v4
}

; check: function %shifted_one_is_nonzero(i64) -> i8 fast {
; check:  block0(v0: i64):
; nextln:     v5 = iconst.i8 1
; nextln:     return v5  ; v5 = 1
; nextln: }
