- // MIR for `has_non_ascii` before LateScalarReplacementOfAggregates
+ // MIR for `has_non_ascii` after LateScalarReplacementOfAggregates
  
  fn has_non_ascii(_1: &[u8]) -> bool {
      debug bytes => _1;
      let mut _0: bool;
      let mut _2: bool;
      let mut _3: std::slice::Iter<'_, u8>;
      let mut _5: std::option::Option<&u8>;
      let mut _6: &mut std::slice::Iter<'_, u8>;
      let mut _7: isize;
      let mut _9: bool;
      let mut _10: bool;
+     let mut _36: std::ptr::NonNull<u8>;
+     let mut _37: *const u8;
+     let mut _38: std::marker::PhantomData<&u8>;
      scope 1 {
          debug has_non_ascii => _0;
          let mut _4: std::slice::Iter<'_, u8>;
+         let mut _39: std::ptr::NonNull<u8>;
+         let mut _40: *const u8;
+         let mut _41: std::marker::PhantomData<&u8>;
+         let mut _42: (*const u8) is !null;
          scope 2 {
-             debug iter => _3;
+             debug ((iter: std::slice::Iter<'_, u8>).0: std::ptr::NonNull<u8>) => _36;
+             debug ((iter: std::slice::Iter<'_, u8>).1: *const u8) => _37;
+             debug ((iter: std::slice::Iter<'_, u8>).2: std::marker::PhantomData<&u8>) => _38;
              let _8: &u8;
              scope 3 {
                  debug byte => _8;
                  scope 38 (inlined core::num::<impl u8>::is_ascii) {
                      let mut _35: u8;
                  }
              }
              scope 20 (inlined <std::slice::Iter<'_, u8> as Iterator>::next) {
                  let _22: std::ptr::NonNull<u8>;
                  let mut _25: usize;
                  let mut _26: bool;
                  let _27: std::ptr::NonNull<u8>;
                  let mut _28: std::ptr::NonNull<u8>;
                  let _29: &u8;
                  scope 21 {
                      let _23: *const u8;
                      scope 22 {
                          let _24: usize;
                          scope 23 {
                              scope 26 (inlined #[track_caller] core::num::<impl usize>::unchecked_sub) {
                                  let _30: ();
                                  scope 27 (inlined core::ub_checks::check_language_ub) {
                                      scope 28 (inlined core::ub_checks::check_language_ub::runtime) {
                                      }
                                  }
                              }
                              scope 29 (inlined without_provenance_mut::<u8>) {
                              }
                          }
                          scope 24 (inlined std::ptr::const_ptr::<impl *const u8>::addr) {
                              scope 25 (inlined std::ptr::const_ptr::<impl *const u8>::cast::<()>) {
                              }
                          }
                          scope 30 (inlined <NonNull<u8> as PartialEq>::eq) {
                              let mut _31: *mut u8;
                              let mut _32: *mut u8;
                              scope 31 (inlined NonNull::<u8>::as_ptr) {
                              }
                              scope 32 (inlined NonNull::<u8>::as_ptr) {
                              }
                          }
                          scope 33 (inlined NonNull::<u8>::add) {
                              let mut _33: *mut u8;
                              scope 34 (inlined NonNull::<u8>::as_ptr) {
                              }
                          }
                          scope 35 (inlined NonNull::<u8>::as_ref::<'_>) {
                              let _34: *const u8;
                              scope 36 (inlined NonNull::<u8>::as_ptr) {
                              }
                              scope 37 (inlined std::ptr::mut_ptr::<impl *mut u8>::cast_const) {
                              }
                          }
                      }
                  }
              }
          }
          scope 4 (inlined core::slice::iter::<impl IntoIterator for &[u8]>::into_iter) {
              scope 5 (inlined core::slice::<impl [u8]>::iter) {
                  scope 6 (inlined std::slice::Iter::<'_, u8>::new) {
                      let _11: usize;
                      let mut _13: std::ptr::NonNull<[u8]>;
                      let mut _15: *mut u8;
                      let mut _16: *mut u8;
                      scope 7 {
                          let _12: std::ptr::NonNull<u8>;
                          scope 8 {
                              let _14: *const u8;
                              scope 9 {
                              }
                              scope 13 (inlined std::ptr::without_provenance::<u8>) {
                                  scope 14 (inlined without_provenance_mut::<u8>) {
                                  }
                              }
                              scope 15 (inlined NonNull::<u8>::as_ptr) {
                              }
                              scope 16 (inlined #[track_caller] std::ptr::mut_ptr::<impl *mut u8>::add) {
                                  let _20: ();
                                  let mut _21: *const ();
                                  scope 17 (inlined core::ub_checks::check_language_ub) {
                                      scope 18 (inlined core::ub_checks::check_language_ub::runtime) {
                                      }
                                  }
                                  scope 19 (inlined std::mem::size_of::<u8>) {
                                  }
                              }
                          }
                          scope 10 (inlined NonNull::<[u8]>::from_ref) {
                              let mut _17: *const [u8];
                          }
                          scope 11 (inlined NonNull::<[u8]>::cast::<u8>) {
                              let mut _18: *mut u8;
                              let mut _19: *mut [u8];
                              scope 12 (inlined NonNull::<[u8]>::as_ptr) {
                              }
                          }
                      }
                  }
              }
          }
      }
  
      bb0: {
          nop;
          _0 = const false;
          nop;
          StorageLive(_14);
          StorageLive(_11);
          _11 = PtrMetadata(copy _1);
          StorageLive(_12);
          StorageLive(_13);
          StorageLive(_17);
          _17 = &raw const (*_1);
          _13 = copy _17 as std::ptr::NonNull<[u8]> (Transmute);
          StorageDead(_17);
          StorageLive(_18);
          StorageLive(_19);
          _19 = copy _13 as *mut [u8] (Transmute);
          _18 = copy _19 as *mut u8 (PtrToPtr);
          StorageDead(_19);
          _12 = copy _18 as std::ptr::NonNull<u8> (Transmute);
          StorageDead(_18);
          StorageDead(_13);
          StorageLive(_15);
          StorageLive(_16);
          _16 = copy _12 as *mut u8 (Transmute);
          _15 = Offset(copy _16, copy _11);
          StorageDead(_16);
          _14 = copy _15 as *const u8 (PtrToPtr);
          StorageDead(_15);
-         _3 = std::slice::Iter::<'_, u8> { ptr: copy _12, end_or_len: copy _14, _marker: const PhantomData::<&u8> };
+         _36 = copy _12;
+         _37 = copy _14;
+         _38 = const PhantomData::<&u8>;
+         nop;
          StorageDead(_12);
          StorageDead(_11);
          StorageDead(_14);
          nop;
          nop;
          goto -> bb1;
      }
  
      bb1: {
          StorageLive(_5);
          StorageLive(_31);
          StorageLive(_22);
-         _22 = copy (_3.0: std::ptr::NonNull<u8>);
+         _22 = copy _36;
          StorageLive(_23);
-         _23 = copy (_3.1: *const u8);
+         _23 = copy _37;
          StorageLive(_26);
          StorageLive(_27);
          _27 = copy _23 as std::ptr::NonNull<u8> (Transmute);
          _31 = copy _22 as *mut u8 (Transmute);
          StorageLive(_32);
          _32 = copy _27 as *mut u8 (Transmute);
          _26 = Eq(copy _31, copy _32);
          StorageDead(_32);
          switchInt(move _26) -> [0: bb3, otherwise: bb2];
      }
  
      bb2: {
          StorageDead(_27);
          StorageDead(_26);
          StorageDead(_23);
          StorageDead(_22);
          StorageDead(_31);
          StorageDead(_5);
          nop;
          nop;
          nop;
          nop;
          return;
      }
  
      bb3: {
          StorageDead(_27);
          StorageDead(_26);
          StorageLive(_28);
          StorageLive(_33);
          _33 = Offset(copy _31, const 1_usize);
          _28 = copy _33 as std::ptr::NonNull<u8> (Transmute);
          StorageDead(_33);
-         (_3.0: std::ptr::NonNull<u8>) = move _28;
+         _36 = move _28;
          StorageDead(_28);
          StorageLive(_29);
          StorageLive(_34);
          _34 = copy _22 as *const u8 (Transmute);
          _29 = &(*_34);
          StorageDead(_34);
          _5 = Option::<&u8>::Some(copy _29);
          StorageDead(_29);
          StorageDead(_23);
          StorageDead(_22);
          StorageDead(_31);
          _8 = copy ((_5 as Some).0: &u8);
          StorageLive(_9);
          StorageLive(_10);
          StorageLive(_35);
          _35 = copy (*_8);
          _10 = Le(move _35, const 127_u8);
          StorageDead(_35);
          _9 = Not(move _10);
          StorageDead(_10);
          _0 = BitOr(copy _0, move _9);
          StorageDead(_9);
          StorageDead(_5);
          goto -> bb1;
      }
  }
  
