test compile precise-output
target aarch64

function %stackslot_reuse(i64, i64) -> i64 {
    ss0 = explicit_slot 8
    ss1 = explicit_slot 8, reuse = ss0

block0(v0: i64, v1: i64):
    stack_store v0, ss0
    v2 = stack_load.i64 ss0
    stack_store v1, ss1
    v3 = stack_load.i64 ss1
    v4 = iadd v2, v3
    return v4
}

; VCode:
;   stp fp, lr, [sp, #-16]!
;   mov fp, sp
;   sub sp, sp, #16
; block0:
;   str x0, [sp]
;   ldr x6, [sp]
;   str x1, [sp]
;   ldr x7, [sp]
;   add x0, x6, x7
;   add sp, sp, #16
;   ldp fp, lr, [sp], #16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   stp x29, x30, [sp, #-0x10]!
;   mov x29, sp
;   sub sp, sp, #0x10
; block1: ; offset 0xc
;   stur x0, [sp]
;   ldur x6, [sp]
;   stur x1, [sp]
;   ldur x7, [sp]
;   add x0, x6, x7
;   add sp, sp, #0x10
;   ldp x29, x30, [sp], #0x10
;   ret
