test inline precise-output
target x86_64

function %callee(i64, i64) -> i64 tail {
    ss0 = explicit_slot 8
    ss1 = explicit_slot 8, reuse = ss0

block0(v0: i64, v1: i64):
    stack_store v0, ss0
    v2 = stack_load.i64 ss0
    stack_store v1, ss1
    v3 = stack_load.i64 ss1
    v4 = iadd v2, v3
    return v4
}

; (no functions inlined into %callee)

function %caller(i64, i64) -> i64 tail {
    ss0 = explicit_slot 4
    fn0 = %callee(i64, i64) -> i64 tail

block0(v0: i64, v1: i64):
    v2 = call fn0(v0, v1)
    return v2
}

; function %caller(i64, i64) -> i64 tail {
;     ss0 = explicit_slot 4
;     ss1 = explicit_slot 8
;     ss2 = explicit_slot 8, reuse = ss1
;     sig0 = (i64, i64) -> i64 tail
;     fn0 = %callee sig0
;
; block0(v0: i64, v1: i64):
;     jump block1
;
; block1:
;     v4 = stack_addr.i64 ss1
;     store.i64 notrap v0, v4
;     v5 = stack_addr.i64 ss1
;     v6 = load.i64 notrap v5
;     v7 = stack_addr.i64 ss2
;     store.i64 notrap v1, v7
;     v8 = stack_addr.i64 ss2
;     v9 = load.i64 notrap v8
;     v10 = iadd v6, v9
;     jump block2(v10)
;
; block2(v3: i64):
;     v2 -> v3
;     return v2
; }
